include:
  - project: "inovacao/devops/template-cicd"
    file: "test-package-js.yaml"
  - project: "inovacao/devops/template-cicd"
    file: "sonar-js.yaml"
  - project: "inovacao/devops/template-cicd"
    file: "publish-package-js.yaml"
  - project: "inovacao/devops/template-cicd"
    file: "copy-package-js.yaml"

test:
  extends: .test

sonar:
  extends: .sonar_js
  variables:
    SONAR_SOURCE: "src"
    SONAR_TEST: "tests"

publish:
  extends: .publish
  script:
    - npm i
    - !reference [.publish, script]

copy:
  extends: .copy

stages:
  - test
  - sonar
  - release
  - copy
