arrowParens: avoid
bracketSameLine: false
bracketSpacing: false
# embeddedLanguageFormatting: auto
insertPragma: false
htmlWhitespaceSensitivity: css
printWidth: 720
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
semi: false
singleAttributePerLine: true
singleQuote: true
trailingComma: all
tabWidth: 4
useTabs: true

overrides:
  - files: '*.svelte'
    options:
      parser: svelte
      plugins:
        - prettier-plugin-svelte
      # svelteSortOrder: options-scripts-markup-styles
      # svelteStrictMode: false
      svelteAllowShorthand: true
      svelteIndentScriptAndStyle: false
  - files: ['*.md', '*.yaml', '*.yml', '*.json', '*.graphql']
    options:
      useTabs: false
      tabWidth: 2
